[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
heapless = "0.9.2"
postcard = "1.1.3"
rusqlite = { version = "0.37.0", features = ["bundled", "chrono"] }
serde = "1.0.228"
uuid = "1.19.0"
